;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	hydra-multiple-cursors/body
	hydra-multiple-cursors/mc/mark-previous-like-this
	mc/toggle-cursor-on-click
	))

(setq mc/cmds-to-run-once
      '(
	hydra-multiple-cursors/mc/mark-next-like-this
	))
